### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by noodlychezzy** [Altoid0/PowerSniper#1]
doesn't it need email to log in? why does it use username? is it intended for ufa?

**Comment by Altoid0** [comment]
So when you log in to minecraft.net it generates a token used to authenticate that account for about 2 hours. and when it PowerSniper tries to snipe the name it sends that token in a POST request to the Mojang servers. Therefore, you don't need to enter the email of the account. As for the username, to send a proper POST request to Mojang's servers you need to include the UUID of the account you are going to change the name on, that's why you need to enter in the current username of the account into PowerSniper. The program will automatically retrieve the UUID of the account you gave it, using the username you entered.

**Comment by Altoid0** [comment]
You can use any type of account with this sniper Except NFA accounts, and maybe UFA. I haven't tested this with UFA accounts and I don't know if the post request looks different for UFA accounts changing their name. However, FA and SFA accounts work 100%.
